config/routes.rb
Muenster::Application.routes.draw do

  resources :jobs
  resources :companies

end

app/models/company.rb
class Company < ActiveRecord::Base
  has_many :jobs

  validates :name, presence: true
  validates :location, presence: true
end

app/models/job.rb
class Job < ActiveRecord::Base
  def self.search(search)
    if search
      find(:all, :conditions => ['title LIKE ?', "%#{search}%"])
    else
      find(:all)
    end
  end

  belongs_to :company

  validates :title, presence: true
  validates :company, presence: true
  validates :description, length: { maximum: 5000 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  def index
    @companies = Company.all
  end

  def show
    @company = Company.find(params[:id])
    @job_lists = @company.jobs
  end

  def new
    @company = Company.new
  end

  def create
    @company = Company.new(company_params)
      if @company.save
      flash[:notice] = "New company added successfully."
      redirect_to @company
    else
      render action: 'new'
    end
  end

   def edit
    @company = Company.find(params[:id])
  end

  def update
  @company = Company.find(params[:id])
    if @company.update(company_params)
      redirect_to @company
    else
      render 'edit'
    end
  end

  private

  def company_params
    params.require(:company).permit(:name, :location ,:description)
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  def index
    @jobs = Job.search(params[:search])
  end

  def show
    @job = Job.find(params[:id])
  end

  def new
    @job = Job.new
  end

  def create
    @job = Job.new(job_params)
     if @job.save
      flash[:notice] = "New job added successfully."
      redirect_to @job
    else
      render action: 'new'
    end
  end

   def edit
    @job = Job.find(params[:id])
  end

  def update
  @job = Job.find(params[:id])
    if @job.update(job_params)
      redirect_to @job
    else
      render 'edit'
    end
  end

  def destroy
    @job = Job.find(params[:id])
    @job.destroy

    redirect_to @job
  end

  private

  def job_params
    params.require(:job).permit(:title, :description, :company_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/companies/edit.html.erb
<h1>Editing Company</h1>

<%= form_for :company, url: company_path(@company), method: :patch do |f| %>
  <% if @company.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@company.errors.count, "error") %> prohibited
      this article from being saved:</h2>
    <ul>
    <% @company.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.label :location %><br>
    <%= f.text_field :location%>
  </p>

  <p>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

<div id="option">
  <%= link_to 'Back', company_path %>
</div>

app/views/companies/index.html.erb
<h2> Companies </h2>

<ul>
  <% @companies.each do |company| %>
    <li>
      <%= link_to company.name, company_path(company) %>
    </li>
  <% end %>
</ul>

app/views/companies/new.html.erb
<h2> Add new company</h2>

<%= form_for @company, url: {action: "create"}, html: {class: "nifty_form"} do |f| %>

   <% if @company.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@company.errors.count, "error") %> prohibited
      this question from being saved:</h2>
    <ul>
    <% @company.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>

  <label>Name: </label><%= f.text_field :name %><br>
  <label>Location: </label><%= f.text_field :location %><br>
  <label>Description: </label><br><%= f.text_area :description, size: "60x12" %><br>
  <%= f.submit "Create" %>
<% end %>

app/views/companies/show.html.erb
<h2><%= @company.name %></h2><br>
<%= link_to "Edit", edit_company_path %><br>

Location: <%= @company.location %></br>
Description: <%= @company.description %>

<h2> Now hiring for these positions: </h2>
<ul>
  <% @job_lists.each do |job| %>
    <li><%= link_to job.title, job_path(job) %> </li>
  <% end %>
</ul>

app/views/jobs/edit.html.erb
<h1>Editing Job</h1>

<%= form_for :job, url: job_path(@job), method: :patch do |f| %>
  <% if @job.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@job.errors.count, "error") %> prohibited
      this article from being saved:</h2>
    <ul>
    <% @job.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

<div id="option">
  <%= link_to 'Back', job_path %>
</div>

app/views/jobs/index.html.erb
<h2> Jobs </h2>
<%= link_to "New Job", new_job_path %>
<ul>
  <% @jobs.each do |job| %>
    <li>
      <%= link_to job.title, job_path(job)  %> - <%= job.company.name %> , <%= job.company.location %>
      </a>
    </li>
  <% end %>
</ul>

app/views/jobs/new.html.erb
<h2> Add new job</h2>

<%= form_for @job, html: {class: "nifty_form"} do |f| %>

   <% if @job.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@job.errors.count, "error") %> prohibited
      this question from being saved:</h2>
    <ul>
    <% @job.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>

  <label>Tile: </label><%= f.text_field :title %><br>
  <label>Description: </label><br><%= f.text_area :description, size: "60x12" %><br>
  <label>Company Name: </label><%= f.collection_select(:company_id, Company.all, :id, :name) %>
  <%= f.submit "Create" %>
<% end %>

app/views/jobs/show.html.erb
Title: <%= @job.title %><br>
Description: <%= @job.description %><br>
Location: <%= @job.company.location %><br>
Company name: <%= @job.company.name %>
<br>
<%= link_to "Home Page", jobs_path %>
<%= link_to "To Company Page", company_path(@job.company) %>
<%= link_to "Edit Job", edit_job_path %>
<%= link_to 'Delete', job_path,
              method: :delete,
              data: { confirm: 'Are you sure?' } %><br>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Muenster</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  Search:
  <%= form_tag jobs_path, :method => 'get'  do %>
  <%= text_field_tag :search, params[:search]%>
  <%= submit_tag "Search", :name => nil  %>
 <% end %>

<%= yield %>

</body>
</html>